title: このまにあ ARイラスト企画
baseurl: ""
url: "https://konomania.github.io"

markdown: kramdown

collections:
  pages:
    output: true
    permalink: /:path

header:
  - name: ANIMAX MUSIX 2021
    url: animax2021
  - name: 鈴フェス Vol.1
    url: suzufesv1

sass:
  style: compressed
